package kasirbfmm;

import javax.swing.*;
import java.awt.*;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



public class barang extends javax.swing.JFrame 
{
  DefaultTableModel model = new DefaultTableModel();
  
  databasee db = new databasee ();
    public barang() {
        this.setUndecorated(true);
        initComponents();
        
        viewdata();
        isianBersih();
        
        db.koneksiDB();
        
        setTanggalOtomatis(); // Memanggil method untuk set tanggal otomatis
        tanggal.setEditable(false);
        
        

        
        jcancel.setOpaque(false);
        jcancel.setContentAreaFilled(false);
        jcancel.setBorderPainted(false);
        jcancel.setFocusPainted(false);
        jcancel.setForeground(Color.WHITE);

        simpan.setOpaque(false);
        simpan.setContentAreaFilled(false);
        simpan.setFocusPainted(false);

        jnm_barang.setOpaque(false);
        jnm_barang.setBackground(new Color(0, 0, 0, 0));
        jkd_barang.setOpaque(false);
        jkd_barang.setBackground(new Color(0, 0, 0, 0));
        jstok.setOpaque(false);
        jstok.setBackground(new Color(0, 0, 0, 0));
        jhrg_jual.setOpaque(false);
        jhrg_jual.setBackground(new Color(0, 0, 0, 0));
        jhrg_beli.setOpaque(false);
        jhrg_beli.setBackground(new Color(0, 0, 0, 0));
        jnm_pemasok.setOpaque(false);
        jnm_pemasok.setBackground(new Color(0, 0, 0, 0));
        jvarian.setOpaque(false);
        jvarian.setBackground(new Color(0, 0, 0, 0));
        jberat.setOpaque(false);
        jberat.setBackground(new Color(0, 0, 0, 0));
        jexp.setOpaque(false);
        jexp.setBackground(new Color(0, 0, 0, 0));
        jbarcode.setOpaque(false);
        jbarcode.setBackground(new Color(0, 0, 0, 0));   
        
        b.setEditable(false); 
        b.setOpaque(false); 
        b.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        b.setFocusable(false); // Biar nggak bisa di-klik
        
        c.setEditable(false); 
        c.setOpaque(false); 
        c.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        c.setFocusable(false); // Biar nggak bisa di-klik
        
        db.koneksiDB();
        
    }
    
     public void viewdata() {
        model.addColumn("Kode");
        model.addColumn("Nama");
        model.addColumn("Harga");
        model.addColumn("Stok");
        model.addColumn("Kategori");
        
        try {
            ResultSet rs=db.ambildata("select * from tb_barang");
            while (rs.next()) {
                model.addRow(new Object[] 
                {rs.getString("kode_barang"),
                    rs.getString("nama_barang"),
//                    rs.getString("varian"),
//                    rs.getString("berat"),
                    rs.getString("harga_jual"),
//                    rs.getString("exp"),
                    rs.getString("stok"),
//                    rs.getString("harga_beli"),
//                    rs.getString("barcode"),
//                    rs.getString("nama_pemasok"),
                    rs.getString("kategori")
                });
                jTable1.setModel(model);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e, "Debug", JOptionPane.ERROR_MESSAGE);
        }
    
    }
          private void isianBersih(){
            jkd_barang.setText("");
            jnm_barang.setText("");
//            jvarian.setText("");
//            jberat.setText("");
            jhrg_jual.setText("");
//            jexp.setText("");
            jstok.setText("");
//            jhrg_beli.setText("");
//            jbarcode.setText("");
//            jnm_pemasok.setText("");
            jkategori.setSelectedItem("");
           }
    
    public void setTanggalOtomatis() {
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd"); // Format tanggal
    String tanggalSekarang = sdf.format(new Date()); // Ambil tanggal sekarang
    tanggal.setText(tanggalSekarang); // Set ke JTextField (ganti dengan nama variabel JTextField tanggal kamu)
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbarang1 = new javax.swing.JDialog();
        jcancel = new javax.swing.JButton();
        tanggal = new javax.swing.JTextField();
        jbarcode = new javax.swing.JTextField();
        noTrans = new javax.swing.JTextField();
        jnm_barang = new javax.swing.JTextField();
        jkd_barang = new javax.swing.JTextField();
        jstok = new javax.swing.JTextField();
        jhrg_jual = new javax.swing.JTextField();
        jhrg_beli = new javax.swing.JTextField();
        jnm_pemasok = new javax.swing.JTextField();
        jvarian = new javax.swing.JTextField();
        jberat = new javax.swing.JTextField();
        jexp = new javax.swing.JTextField();
        simpan = new javax.swing.JButton();
        jkategori = new javax.swing.JComboBox<>();
        c = new javax.swing.JTextField();
        b = new javax.swing.JTextField();
        a = new javax.swing.JLabel();
        jbarang2 = new javax.swing.JDialog();
        jcancel1 = new javax.swing.JButton();
        tanggal1 = new javax.swing.JTextField();
        jbarcode1 = new javax.swing.JTextField();
        noTrans1 = new javax.swing.JTextField();
        jnm_barang1 = new javax.swing.JTextField();
        jkd_barang1 = new javax.swing.JTextField();
        jstok1 = new javax.swing.JTextField();
        jhrg_jual1 = new javax.swing.JTextField();
        jhrg_beli1 = new javax.swing.JTextField();
        jnm_pemasok1 = new javax.swing.JTextField();
        jvarian1 = new javax.swing.JTextField();
        jberat1 = new javax.swing.JTextField();
        jexp1 = new javax.swing.JTextField();
        simpan1 = new javax.swing.JButton();
        jkategori1 = new javax.swing.JComboBox<>();
        c1 = new javax.swing.JTextField();
        b1 = new javax.swing.JTextField();
        a1 = new javax.swing.JLabel();
        tombolHapus = new javax.swing.JButton();
        tombolDasbor1 = new javax.swing.JButton();
        tombolretur = new javax.swing.JButton();
        tombollUser = new javax.swing.JButton();
        tombolLaporan = new javax.swing.JButton();
        tombolLogout1 = new javax.swing.JButton();
        tombolCari1 = new javax.swing.JButton();
        tombolTambah1 = new javax.swing.JButton();
        tombolEdit1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        tombolJual1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jbarang1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jcancel.setBackground(new java.awt.Color(255, 255, 255));
        jcancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/Cancel.png"))); // NOI18N
        jcancel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jcancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcancelActionPerformed(evt);
            }
        });
        jbarang1.getContentPane().add(jcancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, 50, 40));

        tanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanggalActionPerformed(evt);
            }
        });
        jbarang1.getContentPane().add(tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 110, -1));

        jbarcode.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jbarcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbarcodeActionPerformed(evt);
            }
        });
        jbarang1.getContentPane().add(jbarcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, 180, 50));

        noTrans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noTransActionPerformed(evt);
            }
        });
        jbarang1.getContentPane().add(noTrans, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 110, -1));

        jnm_barang.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jnm_barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jnm_barangActionPerformed(evt);
            }
        });
        jbarang1.getContentPane().add(jnm_barang, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 180, 50));

        jkd_barang.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jkd_barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jkd_barangActionPerformed(evt);
            }
        });
        jbarang1.getContentPane().add(jkd_barang, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 180, 50));

        jstok.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jstok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jstokActionPerformed(evt);
            }
        });
        jbarang1.getContentPane().add(jstok, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 180, 50));

        jhrg_jual.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jhrg_jual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jhrg_jualActionPerformed(evt);
            }
        });
        jbarang1.getContentPane().add(jhrg_jual, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 180, 50));

        jhrg_beli.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jhrg_beli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jhrg_beliActionPerformed(evt);
            }
        });
        jbarang1.getContentPane().add(jhrg_beli, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, 180, 50));

        jnm_pemasok.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jnm_pemasok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jnm_pemasokActionPerformed(evt);
            }
        });
        jbarang1.getContentPane().add(jnm_pemasok, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 530, 180, 50));

        jvarian.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jvarian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jvarianActionPerformed(evt);
            }
        });
        jbarang1.getContentPane().add(jvarian, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 180, 50));

        jberat.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jberat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jberatActionPerformed(evt);
            }
        });
        jbarang1.getContentPane().add(jberat, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, 180, 50));

        jexp.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jexp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jexpActionPerformed(evt);
            }
        });
        jbarang1.getContentPane().add(jexp, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, 180, 50));

        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });
        jbarang1.getContentPane().add(simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 530, 130, 50));

        jkategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jbarang1.getContentPane().add(jkategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 460, 140, 40));

        c.setBackground(new java.awt.Color(255, 255, 255));
        c.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jbarang1.getContentPane().add(c, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, -20, 160, 90));

        b.setBackground(new java.awt.Color(255, 255, 255));
        b.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jbarang1.getContentPane().add(b, new org.netbeans.lib.awtextra.AbsoluteConstraints(-92, -34, 150, 60));

        a.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/popup edit dan tambah(1).png"))); // NOI18N
        a.setText("jLabel2");
        jbarang1.getContentPane().add(a, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, -1));

        jbarang2.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jcancel1.setBackground(new java.awt.Color(255, 255, 255));
        jcancel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/Cancel.png"))); // NOI18N
        jcancel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jcancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcancel1ActionPerformed(evt);
            }
        });
        jbarang2.getContentPane().add(jcancel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, 50, 40));

        tanggal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanggal1ActionPerformed(evt);
            }
        });
        jbarang2.getContentPane().add(tanggal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 110, -1));

        jbarcode1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jbarcode1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbarcode1ActionPerformed(evt);
            }
        });
        jbarang2.getContentPane().add(jbarcode1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, 180, 50));

        noTrans1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noTrans1ActionPerformed(evt);
            }
        });
        jbarang2.getContentPane().add(noTrans1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 110, -1));

        jnm_barang1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jnm_barang1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jnm_barang1ActionPerformed(evt);
            }
        });
        jbarang2.getContentPane().add(jnm_barang1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 180, 50));

        jkd_barang1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jkd_barang1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jkd_barang1ActionPerformed(evt);
            }
        });
        jbarang2.getContentPane().add(jkd_barang1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 180, 50));

        jstok1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jstok1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jstok1ActionPerformed(evt);
            }
        });
        jbarang2.getContentPane().add(jstok1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 180, 50));

        jhrg_jual1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jhrg_jual1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jhrg_jual1ActionPerformed(evt);
            }
        });
        jbarang2.getContentPane().add(jhrg_jual1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 180, 50));

        jhrg_beli1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jhrg_beli1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jhrg_beli1ActionPerformed(evt);
            }
        });
        jbarang2.getContentPane().add(jhrg_beli1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, 180, 50));

        jnm_pemasok1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jnm_pemasok1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jnm_pemasok1ActionPerformed(evt);
            }
        });
        jbarang2.getContentPane().add(jnm_pemasok1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 530, 180, 50));

        jvarian1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jvarian1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jvarian1ActionPerformed(evt);
            }
        });
        jbarang2.getContentPane().add(jvarian1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 180, 50));

        jberat1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jberat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jberat1ActionPerformed(evt);
            }
        });
        jbarang2.getContentPane().add(jberat1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, 180, 50));

        jexp1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jexp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jexp1ActionPerformed(evt);
            }
        });
        jbarang2.getContentPane().add(jexp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, 180, 50));

        simpan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpan1ActionPerformed(evt);
            }
        });
        jbarang2.getContentPane().add(simpan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 530, 130, 50));

        jkategori1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jbarang2.getContentPane().add(jkategori1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 460, 140, 40));

        c1.setBackground(new java.awt.Color(255, 255, 255));
        c1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jbarang2.getContentPane().add(c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, -20, 160, 90));

        b1.setBackground(new java.awt.Color(255, 255, 255));
        b1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jbarang2.getContentPane().add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-92, -34, 150, 60));

        a1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/popup edit dan tambah(1).png"))); // NOI18N
        a1.setText("jLabel2");
        jbarang2.getContentPane().add(a1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tombolHapus.setBorderPainted(false);
        tombolHapus.setContentAreaFilled(false);
        tombolHapus.setFocusPainted(false);
        getContentPane().add(tombolHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 100, 120, 40));

        tombolDasbor1.setBorderPainted(false);
        tombolDasbor1.setContentAreaFilled(false);
        tombolDasbor1.setFocusPainted(false);
        tombolDasbor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolDasbor1ActionPerformed(evt);
            }
        });
        getContentPane().add(tombolDasbor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 150, 120, 20));

        tombolretur.setBorderPainted(false);
        tombolretur.setContentAreaFilled(false);
        tombolretur.setFocusPainted(false);
        tombolretur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolreturActionPerformed(evt);
            }
        });
        getContentPane().add(tombolretur, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 100, 20));

        tombollUser.setBorderPainted(false);
        tombollUser.setContentAreaFilled(false);
        tombollUser.setFocusPainted(false);
        tombollUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombollUserActionPerformed(evt);
            }
        });
        getContentPane().add(tombollUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 90, 20));

        tombolLaporan.setBorderPainted(false);
        tombolLaporan.setContentAreaFilled(false);
        tombolLaporan.setFocusPainted(false);
        getContentPane().add(tombolLaporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 120, 20));

        tombolLogout1.setBorderPainted(false);
        tombolLogout1.setContentAreaFilled(false);
        tombolLogout1.setFocusPainted(false);
        tombolLogout1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolLogout1ActionPerformed(evt);
            }
        });
        getContentPane().add(tombolLogout1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 690, 130, 20));

        tombolCari1.setBorderPainted(false);
        tombolCari1.setContentAreaFilled(false);
        tombolCari1.setFocusPainted(false);
        getContentPane().add(tombolCari1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 100, 40, 40));

        tombolTambah1.setBorderPainted(false);
        tombolTambah1.setContentAreaFilled(false);
        tombolTambah1.setFocusPainted(false);
        tombolTambah1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tombolTambah1MouseClicked(evt);
            }
        });
        tombolTambah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolTambah1ActionPerformed(evt);
            }
        });
        getContentPane().add(tombolTambah1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 100, 120, 40));

        tombolEdit1.setBorderPainted(false);
        tombolEdit1.setContentAreaFilled(false);
        tombolEdit1.setFocusPainted(false);
        tombolEdit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolEdit1ActionPerformed(evt);
            }
        });
        getContentPane().add(tombolEdit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 100, 120, 40));

        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextField1.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextField1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextField1.setSelectionColor(new java.awt.Color(255, 255, 255));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 410, 30));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 100, 110, 40));

        jTable1.setBackground(new java.awt.Color(102, 102, 102));
        jTable1.setForeground(new java.awt.Color(204, 204, 204));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Kode", "Nama", "Harga", "Stok", "Kategori"
            }
        ));
        jTable1.setFocusable(false);
        jTable1.setSelectionBackground(new java.awt.Color(204, 204, 204));
        jTable1.setSelectionForeground(new java.awt.Color(76, 52, 98));
        jTable1.setShowGrid(true);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 1020, 540));

        tombolJual1.setBorderPainted(false);
        tombolJual1.setContentAreaFilled(false);
        tombolJual1.setFocusPainted(false);
        tombolJual1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolJual1ActionPerformed(evt);
            }
        });
        getContentPane().add(tombolJual1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 100, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fotoanyarrrrrr/barangg.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void tombolDasbor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolDasbor1ActionPerformed
        dashboard dashboard = new dashboard();
        dashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tombolDasbor1ActionPerformed

    private void tombolreturActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolreturActionPerformed
        jual jual = new jual();
        jual.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tombolreturActionPerformed

    private void tombollUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombollUserActionPerformed
       user user = new user();
       user.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_tombollUserActionPerformed

    private void tombolTambah1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombolTambah1MouseClicked

    }//GEN-LAST:event_tombolTambah1MouseClicked

    private void tombolTambah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolTambah1ActionPerformed
    jbarang1.setSize(580, 660); // Sesuaikan dengan ukuran yang diinginkan
    jbarang1.setLocationRelativeTo(this); // Supaya muncul di tengah
    jbarang1.setModal(true); // Membuat dialog bersifat modal (opsional)
    jbarang1.setVisible(true); // Menampilkan dialog
    
    }//GEN-LAST:event_tombolTambah1ActionPerformed

    private void jcancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcancelActionPerformed
        jbarang1.dispose();  // Tutup JDialog
        this.setVisible(true); // Pastikan JFrame tetap terlihat
    }//GEN-LAST:event_jcancelActionPerformed

    private void tanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tanggalActionPerformed

    private void noTransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noTransActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noTransActionPerformed

    private void jbarcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbarcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbarcodeActionPerformed

    private void jnm_barangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jnm_barangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jnm_barangActionPerformed

    private void jkd_barangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jkd_barangActionPerformed
       try {

            ResultSet rs=db.ambildata("select * from tb_barang where kode_barang='" + jkd_barang.getText() + "'");
            if (rs.next()) {
                jnm_barang.setText( rs.getString("nama_barang"));
                jkd_barang.setText(rs.getString("kode_barang"));
                jhrg_jual.setText( rs.getString("harga_jual"));
                jhrg_beli.setText( rs.getString("harga_beli"));
                jstok.setText( rs.getString("stok"));
                jnm_pemasok.setText( rs.getString("nama_pemasok"));
                jvarian.setText( rs.getString("varian"));
                jberat.setText( rs.getString("berat"));
                jexp.setText( rs.getString("exp"));
                jbarcode.setText( rs.getString("barcode"));
                jkategori.setSelectedItem(rs.getString("kategori"));
                simpan.setEnabled(false);
                // Simpan.setEnabled(false);
                // hapus.setEnabled(false);
            } else {
                JOptionPane.showMessageDialog( null, "Data Belum terdaftar, tambahkan");
                jnm_barang.requestFocus();

            }
        } catch (SQLException e) {
        }
    }//GEN-LAST:event_jkd_barangActionPerformed

    private void jstokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jstokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jstokActionPerformed

    private void jhrg_jualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jhrg_jualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jhrg_jualActionPerformed

    private void jhrg_beliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jhrg_beliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jhrg_beliActionPerformed

    private void jnm_pemasokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jnm_pemasokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jnm_pemasokActionPerformed

    private void jvarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jvarianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jvarianActionPerformed

    private void jberatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jberatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jberatActionPerformed

    private void jexpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jexpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jexpActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
   
                try {
            ResultSet rs = db.ambildata("select * from tb_barang where kode_barang='" + jkd_barang.getText() + "'");
            if (rs.next()) {
                JOptionPane.showMessageDialog(null,"Data telah terdaftar");
                jnm_barang.setText( rs.getString("nama_barang"));
                jstok.setText( rs.getString( "stok"));
                jhrg_jual.setText( rs.getString( "harga_jual"));
                jhrg_beli.setText( rs.getString( "harga_beli"));
                jnm_pemasok.setText( rs.getString( "nama_pemasok"));
                jvarian.setText( rs.getString( "varian"));
                jberat.setText( rs.getString( "berat"));
                jexp.setText( rs.getString( "exp"));
                jbarcode.setText( rs.getString( "barcode"));
                jkategori.setSelectedItem(rs.getString( "kategori"));

            }else{
                db.aksi("insert into tb_barang(kode_barang,nama_barang,kategori,varian,berat,stok,exp,harga_jual,harga_beli,barcode,nama_pemasok)values('"+jkd_barang.getText()+"','"+jnm_barang.getText()+"','"+jkategori.getSelectedItem()+"','"+jvarian.getText()+"','"+jberat.getText()+"','"+jstok.getText()+"','"+jexp.getText()+"','"+jhrg_jual.getText()+"','"+jhrg_beli.getText()+"','"+jbarcode.getText()+"','"+jnm_pemasok.getText()+"')");
                JOptionPane.showMessageDialog(null,"Data telah Disimpan");
                jkd_barang.setText("");
                jnm_barang.setText("");
                jstok.setText("");
                jhrg_jual.setText("");
                jhrg_beli.setText("");
                jnm_pemasok.setText("");
                jvarian.setText("");
                jberat.setText("");
                jexp.setText("");
                jbarcode.setText("");
                jkategori.setSelectedItem("");

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
        
                
        Window window = SwingUtilities.getWindowAncestor(simpan); // Dapatkan parent window
    if (window instanceof JDialog) {
        window.dispose();  // Tutup JDialog
    }
    this.setVisible(true); // Pastikan JFrame tetap terlihat                         
    }//GEN-LAST:event_simpanActionPerformed

    private void tombolLogout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolLogout1ActionPerformed
        login dashboard = new login();
        dashboard.setVisible(true);
        System.out.println("github perubahan");
        this.dispose();
    }//GEN-LAST:event_tombolLogout1ActionPerformed

    private void tombolEdit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolEdit1ActionPerformed
                                 

    }//GEN-LAST:event_tombolEdit1ActionPerformed

    private void jcancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcancel1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcancel1ActionPerformed

    private void tanggal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanggal1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tanggal1ActionPerformed

    private void jbarcode1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbarcode1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbarcode1ActionPerformed

    private void noTrans1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noTrans1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noTrans1ActionPerformed

    private void jnm_barang1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jnm_barang1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jnm_barang1ActionPerformed

    private void jkd_barang1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jkd_barang1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jkd_barang1ActionPerformed

    private void jstok1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jstok1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jstok1ActionPerformed

    private void jhrg_jual1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jhrg_jual1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jhrg_jual1ActionPerformed

    private void jhrg_beli1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jhrg_beli1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jhrg_beli1ActionPerformed

    private void jnm_pemasok1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jnm_pemasok1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jnm_pemasok1ActionPerformed

    private void jvarian1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jvarian1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jvarian1ActionPerformed

    private void jberat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jberat1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jberat1ActionPerformed

    private void jexp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jexp1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jexp1ActionPerformed

    private void simpan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpan1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_simpan1ActionPerformed

    private void tombolJual1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolJual1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tombolJual1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new barang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel a;
    private javax.swing.JLabel a1;
    private javax.swing.JTextField b;
    private javax.swing.JTextField b1;
    private javax.swing.JTextField c;
    private javax.swing.JTextField c1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JDialog jbarang1;
    private javax.swing.JDialog jbarang2;
    private javax.swing.JTextField jbarcode;
    private javax.swing.JTextField jbarcode1;
    private javax.swing.JTextField jberat;
    private javax.swing.JTextField jberat1;
    private javax.swing.JButton jcancel;
    private javax.swing.JButton jcancel1;
    private javax.swing.JTextField jexp;
    private javax.swing.JTextField jexp1;
    private javax.swing.JTextField jhrg_beli;
    private javax.swing.JTextField jhrg_beli1;
    private javax.swing.JTextField jhrg_jual;
    private javax.swing.JTextField jhrg_jual1;
    private javax.swing.JComboBox<String> jkategori;
    private javax.swing.JComboBox<String> jkategori1;
    private javax.swing.JTextField jkd_barang;
    private javax.swing.JTextField jkd_barang1;
    private javax.swing.JTextField jnm_barang;
    private javax.swing.JTextField jnm_barang1;
    private javax.swing.JTextField jnm_pemasok;
    private javax.swing.JTextField jnm_pemasok1;
    private javax.swing.JTextField jstok;
    private javax.swing.JTextField jstok1;
    private javax.swing.JTextField jvarian;
    private javax.swing.JTextField jvarian1;
    private javax.swing.JTextField noTrans;
    private javax.swing.JTextField noTrans1;
    private javax.swing.JButton simpan;
    private javax.swing.JButton simpan1;
    private javax.swing.JTextField tanggal;
    private javax.swing.JTextField tanggal1;
    private javax.swing.JButton tombolCari1;
    private javax.swing.JButton tombolDasbor1;
    private javax.swing.JButton tombolEdit1;
    private javax.swing.JButton tombolHapus;
    private javax.swing.JButton tombolJual1;
    private javax.swing.JButton tombolLaporan;
    private javax.swing.JButton tombolLogout1;
    private javax.swing.JButton tombolTambah1;
    private javax.swing.JButton tombollUser;
    private javax.swing.JButton tombolretur;
    // End of variables declaration//GEN-END:variables

}
