package kasirbfmm;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.net.URL;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

public class barang extends javax.swing.JFrame 
{
    
    public barang() {
        this.setUndecorated(true);
        initComponents();
        setTanggalOtomatis(); // Memanggil method untuk set tanggal otomatis
        tanggal.setEditable(false);
        
        

        
        
        jcancel.setOpaque(false);
        jcancel.setContentAreaFilled(false);
        jcancel.setBorderPainted(false);
        jcancel.setFocusPainted(false);
        jcancel.setForeground(Color.WHITE);

        simpan.setOpaque(false);
        simpan.setContentAreaFilled(false);
        simpan.setFocusPainted(false);

        nama_barang1.setOpaque(false);
        nama_barang1.setBackground(new Color(0, 0, 0, 0));
        kode_barang.setOpaque(false);
        kode_barang.setBackground(new Color(0, 0, 0, 0));
        stok.setOpaque(false);
        stok.setBackground(new Color(0, 0, 0, 0));
        harga_jual.setOpaque(false);
        harga_jual.setBackground(new Color(0, 0, 0, 0));
        harga_beli.setOpaque(false);
        harga_beli.setBackground(new Color(0, 0, 0, 0));
        nama_pemasok.setOpaque(false);
        nama_pemasok.setBackground(new Color(0, 0, 0, 0));
        varian.setOpaque(false);
        varian.setBackground(new Color(0, 0, 0, 0));
        berat.setOpaque(false);
        berat.setBackground(new Color(0, 0, 0, 0));
        exp.setOpaque(false);
        exp.setBackground(new Color(0, 0, 0, 0));
        barcode.setOpaque(false);
        barcode.setBackground(new Color(0, 0, 0, 0));   
        
        b.setEditable(false); 
        b.setOpaque(false); 
        b.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        b.setFocusable(false); // Biar nggak bisa di-klik
        
        c.setEditable(false); 
        c.setOpaque(false); 
        c.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        c.setFocusable(false); // Biar nggak bisa di-klik
    }
    
    
    public void setTanggalOtomatis() {
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd"); // Format tanggal
    String tanggalSekarang = sdf.format(new Date()); // Ambil tanggal sekarang
    tanggal.setText(tanggalSekarang); // Set ke JTextField (ganti dengan nama variabel JTextField tanggal kamu)
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbarang1 = new javax.swing.JDialog();
        jcancel = new javax.swing.JButton();
        tanggal = new javax.swing.JTextField();
        noTrans = new javax.swing.JTextField();
        barcode = new javax.swing.JTextField();
        nama_barang1 = new javax.swing.JTextField();
        kode_barang = new javax.swing.JTextField();
        stok = new javax.swing.JTextField();
        harga_jual = new javax.swing.JTextField();
        harga_beli = new javax.swing.JTextField();
        nama_pemasok = new javax.swing.JTextField();
        varian = new javax.swing.JTextField();
        berat = new javax.swing.JTextField();
        exp = new javax.swing.JTextField();
        simpan = new javax.swing.JButton();
        kategori = new javax.swing.JComboBox<>();
        c = new javax.swing.JTextField();
        b = new javax.swing.JTextField();
        a = new javax.swing.JLabel();
        tombolHapus = new javax.swing.JButton();
        tombolDasbor1 = new javax.swing.JButton();
        tombolBarang1 = new javax.swing.JButton();
        tombolJual = new javax.swing.JButton();
        tombollUser = new javax.swing.JButton();
        tombolLaporan = new javax.swing.JButton();
        tombolLogout1 = new javax.swing.JButton();
        tombolCari1 = new javax.swing.JButton();
        tombolTambah1 = new javax.swing.JButton();
        tombolEdit1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        jbarang1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jcancel.setBackground(new java.awt.Color(255, 255, 255));
        jcancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/Cancel.png"))); // NOI18N
        jcancel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jcancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcancelActionPerformed(evt);
            }
        });
        jbarang1.getContentPane().add(jcancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, 50, 40));

        tanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanggalActionPerformed(evt);
            }
        });
        jbarang1.getContentPane().add(tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 110, -1));

        noTrans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noTransActionPerformed(evt);
            }
        });
        jbarang1.getContentPane().add(noTrans, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 110, -1));

        barcode.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        barcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barcodeActionPerformed(evt);
            }
        });
        jbarang1.getContentPane().add(barcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, 180, 50));

        nama_barang1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        nama_barang1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nama_barang1ActionPerformed(evt);
            }
        });
        jbarang1.getContentPane().add(nama_barang1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 180, 50));

        kode_barang.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        kode_barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kode_barangActionPerformed(evt);
            }
        });
        jbarang1.getContentPane().add(kode_barang, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 180, 50));

        stok.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        stok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stokActionPerformed(evt);
            }
        });
        jbarang1.getContentPane().add(stok, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 180, 50));

        harga_jual.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        harga_jual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                harga_jualActionPerformed(evt);
            }
        });
        jbarang1.getContentPane().add(harga_jual, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 180, 50));

        harga_beli.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        harga_beli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                harga_beliActionPerformed(evt);
            }
        });
        jbarang1.getContentPane().add(harga_beli, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, 180, 50));

        nama_pemasok.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        nama_pemasok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nama_pemasokActionPerformed(evt);
            }
        });
        jbarang1.getContentPane().add(nama_pemasok, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 530, 180, 50));

        varian.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        varian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varianActionPerformed(evt);
            }
        });
        jbarang1.getContentPane().add(varian, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 180, 50));

        berat.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        berat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beratActionPerformed(evt);
            }
        });
        jbarang1.getContentPane().add(berat, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, 180, 50));

        exp.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        exp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expActionPerformed(evt);
            }
        });
        jbarang1.getContentPane().add(exp, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, 180, 50));

        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });
        jbarang1.getContentPane().add(simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 530, 130, 50));

        kategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jbarang1.getContentPane().add(kategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 460, 140, 40));

        c.setBackground(new java.awt.Color(255, 255, 255));
        c.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jbarang1.getContentPane().add(c, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, -20, 160, 90));

        b.setBackground(new java.awt.Color(255, 255, 255));
        b.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jbarang1.getContentPane().add(b, new org.netbeans.lib.awtextra.AbsoluteConstraints(-92, -34, 150, 60));

        a.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/popup edit dan tambah(1).png"))); // NOI18N
        a.setText("jLabel2");
        jbarang1.getContentPane().add(a, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tombolHapus.setBorderPainted(false);
        tombolHapus.setContentAreaFilled(false);
        tombolHapus.setFocusPainted(false);
        getContentPane().add(tombolHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 100, 120, 40));

        tombolDasbor1.setBorderPainted(false);
        tombolDasbor1.setContentAreaFilled(false);
        tombolDasbor1.setFocusPainted(false);
        tombolDasbor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolDasbor1ActionPerformed(evt);
            }
        });
        getContentPane().add(tombolDasbor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 150, 120, 20));

        tombolBarang1.setBorderPainted(false);
        tombolBarang1.setContentAreaFilled(false);
        tombolBarang1.setFocusPainted(false);
        getContentPane().add(tombolBarang1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 120, 20));

        tombolJual.setBorderPainted(false);
        tombolJual.setContentAreaFilled(false);
        tombolJual.setFocusPainted(false);
        tombolJual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolJualActionPerformed(evt);
            }
        });
        getContentPane().add(tombolJual, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 120, 20));

        tombollUser.setBorderPainted(false);
        tombollUser.setContentAreaFilled(false);
        tombollUser.setFocusPainted(false);
        tombollUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombollUserActionPerformed(evt);
            }
        });
        getContentPane().add(tombollUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 120, 20));

        tombolLaporan.setBorderPainted(false);
        tombolLaporan.setContentAreaFilled(false);
        tombolLaporan.setFocusPainted(false);
        getContentPane().add(tombolLaporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 120, 20));

        tombolLogout1.setBorderPainted(false);
        tombolLogout1.setContentAreaFilled(false);
        tombolLogout1.setFocusPainted(false);
        getContentPane().add(tombolLogout1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 690, 130, 20));

        tombolCari1.setBorderPainted(false);
        tombolCari1.setContentAreaFilled(false);
        tombolCari1.setFocusPainted(false);
        getContentPane().add(tombolCari1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 100, 40, 40));

        tombolTambah1.setBorderPainted(false);
        tombolTambah1.setContentAreaFilled(false);
        tombolTambah1.setFocusPainted(false);
        tombolTambah1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tombolTambah1MouseClicked(evt);
            }
        });
        tombolTambah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolTambah1ActionPerformed(evt);
            }
        });
        getContentPane().add(tombolTambah1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 100, 120, 40));

        tombolEdit1.setBorderPainted(false);
        tombolEdit1.setContentAreaFilled(false);
        tombolEdit1.setFocusPainted(false);
        getContentPane().add(tombolEdit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 100, 120, 40));

        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextField1.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextField1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextField1.setSelectionColor(new java.awt.Color(255, 255, 255));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 410, 30));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 100, 110, 40));

        jTable1.setBackground(new java.awt.Color(255, 255, 255));
        jTable1.setForeground(new java.awt.Color(204, 204, 204));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Kode", "Nama", "Harga", "Stok", "Kategori"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setFocusable(false);
        jTable1.setSelectionBackground(new java.awt.Color(204, 204, 204));
        jTable1.setSelectionForeground(new java.awt.Color(76, 52, 98));
        jTable1.setShowGrid(true);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 1020, 540));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/barangg.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void tombolDasbor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolDasbor1ActionPerformed
        dashboard dashboard = new dashboard();
        dashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tombolDasbor1ActionPerformed

    private void tombolJualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolJualActionPerformed
        jual jual = new jual();
        jual.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tombolJualActionPerformed

    private void tombollUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombollUserActionPerformed
       user user = new user();
       user.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_tombollUserActionPerformed

    private void tombolTambah1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombolTambah1MouseClicked

    }//GEN-LAST:event_tombolTambah1MouseClicked

    private void tombolTambah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolTambah1ActionPerformed
    jbarang1.setSize(580, 660); // Sesuaikan dengan ukuran yang diinginkan
    jbarang1.setLocationRelativeTo(this); // Supaya muncul di tengah
    jbarang1.setModal(true); // Membuat dialog bersifat modal (opsional)
    jbarang1.setVisible(true); // Menampilkan dialog
    
    }//GEN-LAST:event_tombolTambah1ActionPerformed

    private void jcancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcancelActionPerformed
        jbarang1.dispose();  // Tutup JDialog
        this.setVisible(true); // Pastikan JFrame tetap terlihat
    }//GEN-LAST:event_jcancelActionPerformed

    private void tanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tanggalActionPerformed

    private void noTransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noTransActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noTransActionPerformed

    private void barcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barcodeActionPerformed

    private void nama_barang1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nama_barang1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nama_barang1ActionPerformed

    private void kode_barangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kode_barangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kode_barangActionPerformed

    private void stokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stokActionPerformed

    private void harga_jualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_harga_jualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_harga_jualActionPerformed

    private void harga_beliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_harga_beliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_harga_beliActionPerformed

    private void nama_pemasokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nama_pemasokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nama_pemasokActionPerformed

    private void varianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_varianActionPerformed

    private void beratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beratActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_beratActionPerformed

    private void expActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
    Window window = SwingUtilities.getWindowAncestor(simpan); // Dapatkan parent window
    if (window instanceof JDialog) {
        window.dispose();  // Tutup JDialog
    }
    this.setVisible(true); // Pastikan JFrame tetap terlihat
    
    }//GEN-LAST:event_simpanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new barang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel a;
    private javax.swing.JTextField b;
    private javax.swing.JTextField barcode;
    private javax.swing.JTextField berat;
    private javax.swing.JTextField c;
    private javax.swing.JTextField exp;
    private javax.swing.JTextField harga_beli;
    private javax.swing.JTextField harga_jual;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JDialog jbarang1;
    private javax.swing.JButton jcancel;
    private javax.swing.JComboBox<String> kategori;
    private javax.swing.JTextField kode_barang;
    private javax.swing.JTextField nama_barang1;
    private javax.swing.JTextField nama_pemasok;
    private javax.swing.JTextField noTrans;
    private javax.swing.JButton simpan;
    private javax.swing.JTextField stok;
    private javax.swing.JTextField tanggal;
    private javax.swing.JButton tombolBarang1;
    private javax.swing.JButton tombolCari1;
    private javax.swing.JButton tombolDasbor1;
    private javax.swing.JButton tombolEdit1;
    private javax.swing.JButton tombolHapus;
    private javax.swing.JButton tombolJual;
    private javax.swing.JButton tombolLaporan;
    private javax.swing.JButton tombolLogout1;
    private javax.swing.JButton tombolTambah1;
    private javax.swing.JButton tombollUser;
    private javax.swing.JTextField varian;
    // End of variables declaration//GEN-END:variables
}
