/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kasirbfmm;

import javax.swing.SwingUtilities;

/**
 *
 * @author user
 */
public class dashboard extends javax.swing.JFrame {
    private String userName;
   
    /**
     * Creates new form dashboard
     */
    
    public dashboard() {
        this(""); // Kalau dipanggil tanpa parameter, default "Guest"
    }
    
    public dashboard(String userName) {
        initComponents();
          this.userName = (userName != null && !userName.isEmpty()) ? userName : " "; 
        nama.setText(this.userName); // Set nama user di JTextField

        // Styling JTextField (readonly, transparan)
        nama.setEditable(false); 
        nama.setOpaque(false); 
        nama.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        
        
        
        // Styling tombol logout transparan
        jlogout.setOpaque(false);
        jlogout.setContentAreaFilled(false);
        jlogout.setBorderPainted(false);
        nama.setText(this.userName); // Set nama user di JTextField

        // Styling JTextField (readonly, transparan)
        nama.setEditable(false); 
        nama.setOpaque(false); 
        nama.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        // Styling tombol logout transparan
        jlogout.setOpaque(false);
        jlogout.setContentAreaFilled(false);
        jlogout.setBorderPainted(false);

        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nama = new javax.swing.JTextField();
        jlogout = new javax.swing.JButton();
        tombolLaba = new javax.swing.JButton();
        tombolDasbor = new javax.swing.JButton();
        tombolBarang1 = new javax.swing.JButton();
        tombolBeli1 = new javax.swing.JButton();
        tombolJual1 = new javax.swing.JButton();
        tomboluser1 = new javax.swing.JButton();
        tombolPembelian1 = new javax.swing.JButton();
        tombolPenjualan1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });
        getContentPane().add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 40, -1, -1));

        jlogout.setBorder(null);
        jlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlogoutActionPerformed(evt);
            }
        });
        getContentPane().add(jlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 720, 120, 30));

        tombolLaba.setBorderPainted(false);
        tombolLaba.setContentAreaFilled(false);
        tombolLaba.setFocusPainted(false);
        tombolLaba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolLabaActionPerformed(evt);
            }
        });
        getContentPane().add(tombolLaba, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, 120, 30));

        tombolDasbor.setBorderPainted(false);
        tombolDasbor.setContentAreaFilled(false);
        tombolDasbor.setFocusPainted(false);
        tombolDasbor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolDasborActionPerformed(evt);
            }
        });
        getContentPane().add(tombolDasbor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 145, 120, 30));

        tombolBarang1.setBorderPainted(false);
        tombolBarang1.setContentAreaFilled(false);
        tombolBarang1.setFocusPainted(false);
        tombolBarang1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolBarang1ActionPerformed(evt);
            }
        });
        getContentPane().add(tombolBarang1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 120, 30));

        tombolBeli1.setBorderPainted(false);
        tombolBeli1.setContentAreaFilled(false);
        tombolBeli1.setFocusPainted(false);
        tombolBeli1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolBeli1ActionPerformed(evt);
            }
        });
        getContentPane().add(tombolBeli1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 120, 30));

        tombolJual1.setBorderPainted(false);
        tombolJual1.setContentAreaFilled(false);
        tombolJual1.setFocusPainted(false);
        tombolJual1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolJual1ActionPerformed(evt);
            }
        });
        getContentPane().add(tombolJual1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 120, 30));

        tomboluser1.setBorderPainted(false);
        tomboluser1.setContentAreaFilled(false);
        tomboluser1.setFocusPainted(false);
        tomboluser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tomboluser1ActionPerformed(evt);
            }
        });
        getContentPane().add(tomboluser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 120, 30));

        tombolPembelian1.setBorderPainted(false);
        tombolPembelian1.setContentAreaFilled(false);
        tombolPembelian1.setFocusPainted(false);
        tombolPembelian1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolPembelian1ActionPerformed(evt);
            }
        });
        getContentPane().add(tombolPembelian1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 120, 30));

        tombolPenjualan1.setBorderPainted(false);
        tombolPenjualan1.setContentAreaFilled(false);
        tombolPenjualan1.setFocusPainted(false);
        tombolPenjualan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolPenjualan1ActionPerformed(evt);
            }
        });
        getContentPane().add(tombolPenjualan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 120, 30));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/desktop.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlogoutActionPerformed
        login dashboard = new login();
        dashboard.setVisible(true);
        System.out.println("github perubahan");
        this.dispose();
    }//GEN-LAST:event_jlogoutActionPerformed

    private void tombolLabaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolLabaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tombolLabaActionPerformed

    private void tombolDasborActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolDasborActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tombolDasborActionPerformed

    private void tombolBarang1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolBarang1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tombolBarang1ActionPerformed

    private void tombolBeli1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolBeli1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tombolBeli1ActionPerformed

    private void tombolJual1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolJual1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tombolJual1ActionPerformed

    private void tomboluser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tomboluser1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tomboluser1ActionPerformed

    private void tombolPembelian1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolPembelian1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tombolPembelian1ActionPerformed

    private void tombolPenjualan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolPenjualan1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tombolPenjualan1ActionPerformed

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jlogout;
    private javax.swing.JTextField nama;
    private javax.swing.JButton tombolBarang1;
    private javax.swing.JButton tombolBeli1;
    private javax.swing.JButton tombolDasbor;
    private javax.swing.JButton tombolJual1;
    private javax.swing.JButton tombolLaba;
    private javax.swing.JButton tombolPembelian1;
    private javax.swing.JButton tombolPenjualan1;
    private javax.swing.JButton tomboluser1;
    // End of variables declaration//GEN-END:variables
}
