/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kasirbfmm;

/**
 *
 * @author Dhimas Ananta
 */
public class jual extends javax.swing.JFrame {

    /**
     * Creates new form jual
     */
    public jual() {
        this.setUndecorated(true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barang = new javax.swing.JButton();
        dasbor1 = new javax.swing.JButton();
        barang1 = new javax.swing.JButton();
        jual = new javax.swing.JButton();
        user = new javax.swing.JButton();
        laporan = new javax.swing.JButton();
        logout1 = new javax.swing.JButton();
        simpan = new javax.swing.JButton();
        hapus1 = new javax.swing.JButton();
        tambah2 = new javax.swing.JButton();
        cetak1 = new javax.swing.JButton();
        ekspor1 = new javax.swing.JButton();
        tanggal = new javax.swing.JTextField();
        noTransaksi1 = new javax.swing.JTextField();
        namaBarang = new javax.swing.JTextField();
        kembalian = new javax.swing.JTextField();
        kodeBarang2 = new javax.swing.JTextField();
        harga1 = new javax.swing.JTextField();
        stok1 = new javax.swing.JTextField();
        qty1 = new javax.swing.JTextField();
        jumlahHarga1 = new javax.swing.JTextField();
        total1 = new javax.swing.JTextField();
        bayar1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        barang.setBorderPainted(false);
        barang.setContentAreaFilled(false);
        barang.setFocusPainted(false);
        getContentPane().add(barang, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 360, 120, 40));

        dasbor1.setBorderPainted(false);
        dasbor1.setContentAreaFilled(false);
        dasbor1.setFocusPainted(false);
        dasbor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dasbor1ActionPerformed(evt);
            }
        });
        getContentPane().add(dasbor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 110, 20));

        barang1.setBorderPainted(false);
        barang1.setContentAreaFilled(false);
        barang1.setFocusPainted(false);
        barang1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barang1ActionPerformed(evt);
            }
        });
        getContentPane().add(barang1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 110, 20));

        jual.setBorderPainted(false);
        jual.setContentAreaFilled(false);
        jual.setFocusPainted(false);
        getContentPane().add(jual, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 110, 20));

        user.setBorderPainted(false);
        user.setContentAreaFilled(false);
        user.setFocusPainted(false);
        getContentPane().add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 110, 20));

        laporan.setBorderPainted(false);
        laporan.setContentAreaFilled(false);
        laporan.setFocusPainted(false);
        getContentPane().add(laporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 110, 20));

        logout1.setBorderPainted(false);
        logout1.setContentAreaFilled(false);
        logout1.setFocusPainted(false);
        getContentPane().add(logout1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 690, 130, 30));

        simpan.setBorderPainted(false);
        simpan.setContentAreaFilled(false);
        simpan.setFocusPainted(false);
        getContentPane().add(simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 680, 130, 40));

        hapus1.setBorderPainted(false);
        hapus1.setContentAreaFilled(false);
        hapus1.setFocusPainted(false);
        getContentPane().add(hapus1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 360, 130, 40));

        tambah2.setBorderPainted(false);
        tambah2.setContentAreaFilled(false);
        tambah2.setFocusPainted(false);
        getContentPane().add(tambah2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, 130, 40));

        cetak1.setBorderPainted(false);
        cetak1.setContentAreaFilled(false);
        cetak1.setFocusPainted(false);
        getContentPane().add(cetak1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 680, 130, 40));

        ekspor1.setBorderPainted(false);
        ekspor1.setContentAreaFilled(false);
        ekspor1.setFocusPainted(false);
        getContentPane().add(ekspor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 680, 130, 40));

        tanggal.setBackground(new java.awt.Color(153, 153, 153));
        tanggal.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 110, 20));

        noTransaksi1.setBackground(new java.awt.Color(153, 153, 153));
        noTransaksi1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(noTransaksi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 110, 20));

        namaBarang.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(namaBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 210, 450, 30));

        kembalian.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(kembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 690, 100, 30));

        kodeBarang2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(kodeBarang2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 209, 450, 30));

        harga1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(harga1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 190, 30));

        stok1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(stok1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 300, 190, 30));

        qty1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(qty1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 300, 190, 30));

        jumlahHarga1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(jumlahHarga1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 300, 190, 30));

        total1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(total1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 690, 100, 30));

        bayar1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(bayar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 690, 100, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Kode", "Nama", "Qty", "Harga satuan"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 422, 1020, 230));

        jLabel1.setBackground(new java.awt.Color(153, 153, 153));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/jual.png"))); // NOI18N
        jLabel1.setText(" ");
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, -10, 1380, 780));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void barang1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barang1ActionPerformed
        barang barang = new barang();
        barang.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_barang1ActionPerformed

    private void dasbor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dasbor1ActionPerformed
        dashboard dashboard = new dashboard();
        dashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dasbor1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jual().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton barang;
    private javax.swing.JButton barang1;
    private javax.swing.JTextField bayar1;
    private javax.swing.JButton cetak1;
    private javax.swing.JButton dasbor1;
    private javax.swing.JButton ekspor1;
    private javax.swing.JButton hapus1;
    private javax.swing.JTextField harga1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jual;
    private javax.swing.JTextField jumlahHarga1;
    private javax.swing.JTextField kembalian;
    private javax.swing.JTextField kodeBarang2;
    private javax.swing.JButton laporan;
    private javax.swing.JButton logout1;
    private javax.swing.JTextField namaBarang;
    private javax.swing.JTextField noTransaksi1;
    private javax.swing.JTextField qty1;
    private javax.swing.JButton simpan;
    private javax.swing.JTextField stok1;
    private javax.swing.JButton tambah2;
    private javax.swing.JTextField tanggal;
    private javax.swing.JTextField total1;
    private javax.swing.JButton user;
    // End of variables declaration//GEN-END:variables
}
