/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kasirbfmm;

/**
 *
 * @author Dhimas Ananta
 */
public class kartustok extends javax.swing.JFrame {

    /**
     * Creates new form kartustok
     */
    public kartustok() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        stokAkhir = new javax.swing.JTextField();
        kodeBarang1 = new javax.swing.JTextField();
        namaBarang1 = new javax.swing.JTextField();
        stokKeluar1 = new javax.swing.JTextField();
        stokMasuk1 = new javax.swing.JTextField();
        silang = new javax.swing.JButton();
        simpan1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        stokAkhir.setBorder(null);
        stokAkhir.setOpaque(false);
        stokAkhir.setRequestFocusEnabled(false);
        getContentPane().add(stokAkhir, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 130, 30));

        kodeBarang1.setBorder(null);
        kodeBarang1.setOpaque(false);
        kodeBarang1.setRequestFocusEnabled(false);
        getContentPane().add(kodeBarang1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 210, 30));

        namaBarang1.setBorder(null);
        namaBarang1.setOpaque(false);
        namaBarang1.setRequestFocusEnabled(false);
        getContentPane().add(namaBarang1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 210, 30));

        stokKeluar1.setBorder(null);
        stokKeluar1.setOpaque(false);
        stokKeluar1.setRequestFocusEnabled(false);
        getContentPane().add(stokKeluar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 130, 30));

        stokMasuk1.setBorder(null);
        stokMasuk1.setOpaque(false);
        stokMasuk1.setRequestFocusEnabled(false);
        getContentPane().add(stokMasuk1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 130, 30));

        silang.setBorder(null);
        silang.setBorderPainted(false);
        silang.setContentAreaFilled(false);
        silang.setFocusPainted(false);
        silang.setRequestFocusEnabled(false);
        getContentPane().add(silang, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, 30, 30));

        simpan1.setBorder(null);
        simpan1.setBorderPainted(false);
        simpan1.setContentAreaFilled(false);
        simpan1.setFocusPainted(false);
        simpan1.setRequestFocusEnabled(false);
        getContentPane().add(simpan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 230, 470, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fotobaru/kartus stok.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-19, -20, 640, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kartustok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kartustok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kartustok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kartustok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kartustok().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField kodeBarang1;
    private javax.swing.JTextField namaBarang1;
    private javax.swing.JButton silang;
    private javax.swing.JButton simpan1;
    private javax.swing.JTextField stokAkhir;
    private javax.swing.JTextField stokKeluar1;
    private javax.swing.JTextField stokMasuk1;
    // End of variables declaration//GEN-END:variables
}
