/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kasirbfmm;

/**
 *
 * @author Dhimas Ananta
 */
public class pembelian extends javax.swing.JFrame {

    /**
     * Creates new form pembelian
     */
    public pembelian() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        laba = new javax.swing.JButton();
        dasbor1 = new javax.swing.JButton();
        barang1 = new javax.swing.JButton();
        jual1 = new javax.swing.JButton();
        user1 = new javax.swing.JButton();
        laporan1 = new javax.swing.JButton();
        logout1 = new javax.swing.JButton();
        ekspor1 = new javax.swing.JButton();
        pembelian1 = new javax.swing.JButton();
        penjualan1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        sampaiTanggal = new javax.swing.JTextField();
        dariTanggal1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        laba.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        laba.setBorderPainted(false);
        laba.setContentAreaFilled(false);
        laba.setFocusPainted(false);
        getContentPane().add(laba, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 100, 120, 40));

        dasbor1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        dasbor1.setBorderPainted(false);
        dasbor1.setContentAreaFilled(false);
        dasbor1.setFocusPainted(false);
        getContentPane().add(dasbor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 100, 20));

        barang1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        barang1.setBorderPainted(false);
        barang1.setContentAreaFilled(false);
        barang1.setFocusPainted(false);
        getContentPane().add(barang1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 100, 20));

        jual1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jual1.setBorderPainted(false);
        jual1.setContentAreaFilled(false);
        jual1.setFocusPainted(false);
        getContentPane().add(jual1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 80, 20));

        user1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        user1.setBorderPainted(false);
        user1.setContentAreaFilled(false);
        user1.setFocusPainted(false);
        getContentPane().add(user1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 80, 20));

        laporan1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        laporan1.setBorderPainted(false);
        laporan1.setContentAreaFilled(false);
        laporan1.setFocusPainted(false);
        getContentPane().add(laporan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 110, 20));

        logout1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        logout1.setBorderPainted(false);
        logout1.setContentAreaFilled(false);
        logout1.setFocusPainted(false);
        getContentPane().add(logout1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 690, 100, 30));

        ekspor1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ekspor1.setBorderPainted(false);
        ekspor1.setContentAreaFilled(false);
        ekspor1.setFocusPainted(false);
        getContentPane().add(ekspor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 680, 120, 40));

        pembelian1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        pembelian1.setBorderPainted(false);
        pembelian1.setContentAreaFilled(false);
        pembelian1.setFocusPainted(false);
        getContentPane().add(pembelian1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 100, 120, 40));

        penjualan1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        penjualan1.setBorderPainted(false);
        penjualan1.setContentAreaFilled(false);
        penjualan1.setFocusPainted(false);
        getContentPane().add(penjualan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 100, 120, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "No transaksi", "Kode", "Nama barang", "Tanggal", "Harga satuan", "Total harga", "Jumlah terjual"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
            jTable1.getColumnModel().getColumn(6).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 1000, 450));

        sampaiTanggal.setBackground(new java.awt.Color(153, 153, 153));
        sampaiTanggal.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        sampaiTanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sampaiTanggalActionPerformed(evt);
            }
        });
        getContentPane().add(sampaiTanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, 110, -1));

        dariTanggal1.setBackground(new java.awt.Color(153, 153, 153));
        dariTanggal1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        dariTanggal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dariTanggal1ActionPerformed(evt);
            }
        });
        getContentPane().add(dariTanggal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 110, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/pembeliann.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sampaiTanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sampaiTanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sampaiTanggalActionPerformed

    private void dariTanggal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dariTanggal1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dariTanggal1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pembelian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton barang1;
    private javax.swing.JTextField dariTanggal1;
    private javax.swing.JButton dasbor1;
    private javax.swing.JButton ekspor1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jual1;
    private javax.swing.JButton laba;
    private javax.swing.JButton laporan1;
    private javax.swing.JButton logout1;
    private javax.swing.JButton pembelian1;
    private javax.swing.JButton penjualan1;
    private javax.swing.JTextField sampaiTanggal;
    private javax.swing.JButton user1;
    // End of variables declaration//GEN-END:variables
}
