/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kasirbfmm;

/**
 *
 * @author Dhimas Ananta
 */
public class retur extends javax.swing.JFrame {

    /**
     * Creates new form retur
     */
    public retur() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tombolhapus = new javax.swing.JButton();
        tombollogout = new javax.swing.JButton();
        tombolbarang1 = new javax.swing.JButton();
        tomboljual1 = new javax.swing.JButton();
        tomboluser1 = new javax.swing.JButton();
        tombollaporan1 = new javax.swing.JButton();
        tomboldasbor1 = new javax.swing.JButton();
        tombolcari1 = new javax.swing.JButton();
        tomboltambah1 = new javax.swing.JButton();
        tomboledit1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tombolhapus.setBorderPainted(false);
        tombolhapus.setContentAreaFilled(false);
        tombolhapus.setFocusPainted(false);
        tombolhapus.setFocusable(false);
        tombolhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolhapusActionPerformed(evt);
            }
        });
        getContentPane().add(tombolhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 100, 130, 40));

        tombollogout.setBorderPainted(false);
        tombollogout.setContentAreaFilled(false);
        tombollogout.setFocusPainted(false);
        tombollogout.setFocusable(false);
        getContentPane().add(tombollogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 690, 110, 20));

        tombolbarang1.setBorderPainted(false);
        tombolbarang1.setContentAreaFilled(false);
        tombolbarang1.setFocusPainted(false);
        tombolbarang1.setFocusable(false);
        getContentPane().add(tombolbarang1, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 200, 100, 20));

        tomboljual1.setBorderPainted(false);
        tomboljual1.setContentAreaFilled(false);
        tomboljual1.setFocusPainted(false);
        tomboljual1.setFocusable(false);
        getContentPane().add(tomboljual1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 90, 20));

        tomboluser1.setBorderPainted(false);
        tomboluser1.setContentAreaFilled(false);
        tomboluser1.setFocusPainted(false);
        tomboluser1.setFocusable(false);
        getContentPane().add(tomboluser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 90, 20));

        tombollaporan1.setBorderPainted(false);
        tombollaporan1.setContentAreaFilled(false);
        tombollaporan1.setFocusPainted(false);
        tombollaporan1.setFocusable(false);
        getContentPane().add(tombollaporan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 110, 20));

        tomboldasbor1.setBorderPainted(false);
        tomboldasbor1.setContentAreaFilled(false);
        tomboldasbor1.setFocusPainted(false);
        tomboldasbor1.setFocusable(false);
        tomboldasbor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tomboldasbor1ActionPerformed(evt);
            }
        });
        getContentPane().add(tomboldasbor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 110, 20));

        tombolcari1.setBorderPainted(false);
        tombolcari1.setContentAreaFilled(false);
        tombolcari1.setFocusPainted(false);
        tombolcari1.setFocusable(false);
        tombolcari1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolcari1ActionPerformed(evt);
            }
        });
        getContentPane().add(tombolcari1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 100, -1, 40));

        tomboltambah1.setBorderPainted(false);
        tomboltambah1.setContentAreaFilled(false);
        tomboltambah1.setFocusPainted(false);
        tomboltambah1.setFocusable(false);
        tomboltambah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tomboltambah1ActionPerformed(evt);
            }
        });
        getContentPane().add(tomboltambah1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 100, 120, 40));

        tomboledit1.setBorderPainted(false);
        tomboledit1.setContentAreaFilled(false);
        tomboledit1.setFocusPainted(false);
        tomboledit1.setFocusable(false);
        tomboledit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tomboledit1ActionPerformed(evt);
            }
        });
        getContentPane().add(tomboledit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 100, 130, 40));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 100, 130, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Kode Barang", "Nama Barang", "Qty", "Kategori", "Alazan", "Tanggal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 162, 1020, 530));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fotoanyarrrrrr/retur.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tombolhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolhapusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tombolhapusActionPerformed

    private void tomboldasbor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tomboldasbor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tomboldasbor1ActionPerformed

    private void tombolcari1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolcari1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tombolcari1ActionPerformed

    private void tomboltambah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tomboltambah1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tomboltambah1ActionPerformed

    private void tomboledit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tomboledit1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tomboledit1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(retur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(retur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(retur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(retur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new retur().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton tombolbarang1;
    private javax.swing.JButton tombolcari1;
    private javax.swing.JButton tomboldasbor1;
    private javax.swing.JButton tomboledit1;
    private javax.swing.JButton tombolhapus;
    private javax.swing.JButton tomboljual1;
    private javax.swing.JButton tombollaporan1;
    private javax.swing.JButton tombollogout;
    private javax.swing.JButton tomboltambah1;
    private javax.swing.JButton tomboluser1;
    // End of variables declaration//GEN-END:variables
}
