/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kasirbfmm;

/**
 *
 * @author Dhimas Ananta
 */
public class user extends javax.swing.JFrame {

    /**
     * Creates new form user
     */
    public user() {
        this.setUndecorated(true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dasbor1 = new javax.swing.JButton();
        barang1 = new javax.swing.JButton();
        jual = new javax.swing.JButton();
        stokOp = new javax.swing.JButton();
        laporan = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        hapus1 = new javax.swing.JButton();
        rfid = new javax.swing.JTextField();
        idUserbaeu1 = new javax.swing.JTextField();
        username1 = new javax.swing.JTextField();
        nama1 = new javax.swing.JTextField();
        logout2 = new javax.swing.JButton();
        simpan2 = new javax.swing.JButton();
        retur1 = new javax.swing.JButton();
        kataSandi1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        retur2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dasbor1.setBorderPainted(false);
        dasbor1.setContentAreaFilled(false);
        dasbor1.setFocusPainted(false);
        getContentPane().add(dasbor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 100, 20));

        barang1.setBorderPainted(false);
        barang1.setContentAreaFilled(false);
        barang1.setFocusPainted(false);
        getContentPane().add(barang1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 100, 20));

        jual.setBorderPainted(false);
        jual.setContentAreaFilled(false);
        jual.setFocusPainted(false);
        getContentPane().add(jual, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 80, 20));

        stokOp.setBorderPainted(false);
        stokOp.setContentAreaFilled(false);
        stokOp.setFocusPainted(false);
        getContentPane().add(stokOp, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 110, 20));

        laporan.setBorderPainted(false);
        laporan.setContentAreaFilled(false);
        laporan.setFocusPainted(false);
        getContentPane().add(laporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 120, 20));

        hapus.setBorderPainted(false);
        hapus.setContentAreaFilled(false);
        hapus.setFocusPainted(false);
        getContentPane().add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 260, 120, 40));

        hapus1.setBorderPainted(false);
        hapus1.setContentAreaFilled(false);
        hapus1.setFocusPainted(false);
        getContentPane().add(hapus1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 330, 130, 40));

        rfid.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        rfid.setOpaque(false);
        getContentPane().add(rfid, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 190, 210, 40));

        idUserbaeu1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        idUserbaeu1.setOpaque(false);
        getContentPane().add(idUserbaeu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 430, 40));

        username1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        username1.setOpaque(false);
        getContentPane().add(username1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 440, 30));

        nama1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        nama1.setOpaque(false);
        getContentPane().add(nama1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 100, 450, 40));

        logout2.setBorderPainted(false);
        logout2.setContentAreaFilled(false);
        logout2.setFocusPainted(false);
        getContentPane().add(logout2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 690, 100, 30));

        simpan2.setBorderPainted(false);
        simpan2.setContentAreaFilled(false);
        simpan2.setFocusPainted(false);
        getContentPane().add(simpan2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 130, 40));

        retur1.setBorderPainted(false);
        retur1.setContentAreaFilled(false);
        retur1.setFocusPainted(false);
        getContentPane().add(retur1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 100, 20));

        kataSandi1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        kataSandi1.setOpaque(false);
        getContentPane().add(kataSandi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 190, 210, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id user", "Nama user", "Username", "Kata Sandi", "Rfid"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 320, 1010, 380));

        retur2.setBorderPainted(false);
        retur2.setContentAreaFilled(false);
        retur2.setFocusPainted(false);
        getContentPane().add(retur2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 90, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fotobaru/user.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new user().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton barang1;
    private javax.swing.JButton dasbor1;
    private javax.swing.JButton hapus;
    private javax.swing.JButton hapus1;
    private javax.swing.JTextField idUserbaeu1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jual;
    private javax.swing.JTextField kataSandi1;
    private javax.swing.JButton laporan;
    private javax.swing.JButton logout2;
    private javax.swing.JTextField nama1;
    private javax.swing.JButton retur1;
    private javax.swing.JButton retur2;
    private javax.swing.JTextField rfid;
    private javax.swing.JButton simpan2;
    private javax.swing.JButton stokOp;
    private javax.swing.JTextField username1;
    // End of variables declaration//GEN-END:variables
}
